### ISSUE TITLE
Fails with perls < 5.10

### ISSUE THREAD

**Issue by andk** [doy/www-ynab#1]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/5ba72c76-77ee-11e8-b06b-ddc9c07fc067

Interesting incompatibility which I see for the first time, I think. Before perl 5.10 a construct like

((main->foo)[0][0])

was a syntax error, one had to write something like

(main->foo->[0])
or
((main->foo)[0]->[0])

**Comment by doy** [comment]
fixed in b9f61cb, thanks!
